// 截图 → asset-descriptions.md。
// 官方金样本因没配 Vision key，描述很弱（"dashboard.jpg — dashboard"）；
// 我们用 StepFun 多模态给关键截图生成视觉级描述，喂给下游 Step3 分镜编导。
import { callStepMessages } from "../lib/step-client"
import { logger } from "../lib/logger"
import type { ScreenshotMetadata } from "../types/capture"

export interface AssetToDescribe {
  /** 相对 capture/ 的路径，如 assets/00-dashboard.png */
  path: string
  label: string
  metadata: ScreenshotMetadata
  buffer: Buffer
  /** 图片 MIME（默认 image/png） */
  mediaType?: string
}

const VISION_SYSTEM =
  "You write concise, factual asset descriptions for a product demo video storyboard. " +
  "Reply with ONE English sentence describing what UI or feature the screenshot shows. " +
  "No preamble, no markdown, no bullet points, no guessing beyond what is visible."

/** 折叠成单行（asset-descriptions.md 每资产一行） */
function oneLine(s: string): string {
  return s.replace(/\s+/g, " ").trim()
}

/** 目录派生描述（无 Vision 时的兜底，等价官方无 key 的行为，但带上 aiDecision 语境） */
function catalogDescription(a: AssetToDescribe): string {
  const bits: string[] = []
  const label = oneLine(a.label || "")
  if (label) bits.push(label)
  if (a.metadata.pageType) bits.push(a.metadata.pageType)
  if (a.metadata.aiDecision) bits.push(a.metadata.aiDecision)
  return bits.join(" — ") || "screenshot"
}

/** 用 StepFun 多模态描述单张截图；失败则抛出由上层降级 */
async function visionDescribe(a: AssetToDescribe): Promise<string> {
  // 视觉模型：step-3.7-flash（step-explore 不吃图片）。它是推理模型，会先产 thinking 块，
  // 故 maxTokens 要留出思考预算 + effort:low 收敛，否则 token 全耗在 thinking 上、正文为空。
  const text = await callStepMessages({
    model: process.env.STEP_VISION_MODEL || "step-3.7-flash",
    effort: "low",
    system: VISION_SYSTEM,
    maxTokens: 800,
    content: [
      {
        type: "text",
        text:
          `Screenshot label: ${a.label || "(none)"}. ` +
          `Page type: ${a.metadata.pageType || "unknown"}. ` +
          `Describe what this screen shows in one sentence.`,
      },
      {
        type: "image",
        source: {
          type: "base64",
          media_type: a.mediaType || "image/png",
          data: a.buffer.toString("base64"),
        },
      },
    ],
  })
  // 模型偶尔会包一层 JSON 或引号，做一次宽松清洗
  const cleaned = oneLine(text).replace(/^["'“”]+|["'“”]+$/g, "")
  return cleaned
}

export interface DescribeResult {
  markdown: string
  /** path → 最终描述（供 manifest 记录） */
  descriptions: Map<string, string>
  visionUsed: boolean
}

/**
 * 生成 asset-descriptions.md。
 * @param assets 已确定落盘路径的截图
 * @param useVision 是否启用 StepFun 视觉描述（无 STEP_API_KEY 时自动降级）
 */
export async function describeAssets(
  assets: AssetToDescribe[],
  useVision: boolean
): Promise<DescribeResult> {
  const hasKey = !!process.env.STEP_API_KEY
  const doVision = useVision && hasKey
  const descriptions = new Map<string, string>()
  let visionUsed = false

  for (const a of assets) {
    let desc = catalogDescription(a)
    if (doVision) {
      try {
        const v = await visionDescribe(a)
        if (v) {
          desc = v
          visionUsed = true
        }
      } catch (err) {
        logger.warn("adapter:vision_describe_failed", { path: a.path, error: String(err) })
        // 保留目录派生描述作为兜底
      }
    }
    descriptions.set(a.path, desc)
  }

  const header = doVision
    ? "# Asset Descriptions\n\n> Vision descriptions generated by StepFun (step-explore).\n"
    : "# Asset Descriptions\n\n> Catalog-derived descriptions (Vision disabled or STEP_API_KEY unset).\n"

  const body = assets.map((a) => `- ${a.path} — ${descriptions.get(a.path)}`).join("\n")
  const markdown = `${header}\n${body}\n`

  return { markdown, descriptions, visionUsed }
}
