// All 13 HyperFrames frame presets, extracted from .qoder/skills/hyperframes-creative/frame-presets/.
// Each preset contains real palette, type ramp, tags, and composition rules from its FRAME.md.
import type { FramePreset } from "./types.js"

export const FRAME_PRESETS: FramePreset[] = [
  {
    id: "cobalt-grid",
    name: "Cobalt Grid",
    palette: {
      ink: "#1F2BE0",
      canvas: "#F0EBDE",
      accents: ["#1F2BE0", "#5560E5"],
      muted: "#8B8570",
    },
    typeRamp: {
      display: "Newsreader",
      heading: "Newsreader",
      body: "Hanken Grotesk",
      mono: "DM Mono",
      scale: [0.78, 0.83, 0.95, 1.5, 2.1, 4.6, 6.8, 10.4],
    },
    tags: ["editorial", "serif", "grid", "technical", "light", "newspaper"],
    compositionRules: [
      "Permanent graph-paper grid behind every frame at 10% ink opacity",
      "Two persistent cobalt hairlines framing every composition",
      "Newsreader serif 400 for display, Hanken Grotesk for body, DM Mono for data",
      "Pixel-glitch stair-stepped scanline column as decorative signature",
      "QR-block mosaic patch as corner punctuation",
    ],
  },
  {
    id: "capsule",
    name: "Capsule",
    palette: {
      ink: "#1A1A1A",
      canvas: "#F5F5F0",
      accents: ["#E85D4E", "#C4D94E", "#C5B5E0", "#8BB4F7"],
      muted: "#8A8A85",
    },
    typeRamp: {
      display: "Bodoni Moda",
      heading: "Bodoni Moda",
      body: "Space Grotesk",
      mono: "JetBrains Mono",
      scale: [0.75, 0.85, 0.95, 1.9, 4.0, 5.0, 8.5, 12.0],
    },
    tags: ["playful", "candy", "pill", "colorful", "light", "fun", "creative"],
    compositionRules: [
      "Pill geometry (9999px small / 2rem cards) with 2px ink outline on everything",
      "Sun-bleached cream canvas with nine-color candy palette",
      "Soft hard-offset shadows (4/6/8/12px in 8% ink)",
      "Floating decorative-pill wallpaper and radial accent glows",
      "Grain overlay for texture",
    ],
  },
  {
    id: "cartesian",
    name: "Cartesian",
    palette: {
      ink: "#1A1A1A",
      canvas: "#EDE8E0",
      accents: ["#8A8178"],
      muted: "#5A5A5A",
    },
    typeRamp: {
      display: "Playfair Display",
      heading: "Playfair Display",
      body: "Inter",
      mono: "JetBrains Mono",
      scale: [0.85, 1.0, 1.3, 1.8, 4.0, 6.2, 8.0],
    },
    tags: ["editorial", "restrained", "elegant", "light", "warm", "minimal"],
    compositionRules: [
      "Five-tone warm-stone palette with universal 1px taupe hairline",
      "Compass-drafted geometric rings as background decoration",
      "Zero shadow / zero fill — restraint is the rule",
      "Playfair Display 400 sentence-case display + Inter body",
      "Cards use faint white-overlay fill so canvas bleeds through",
    ],
  },
  {
    id: "coral",
    name: "Coral",
    palette: {
      ink: "#1A1A1A",
      canvas: "#F5F0E8",
      accents: ["#E85D5D", "#D44A4A"],
      muted: "#6B6B6B",
    },
    typeRamp: {
      display: "Bebas Neue",
      heading: "Bebas Neue",
      body: "Inter",
      mono: "JetBrains Mono",
      scale: [1.0, 1.5, 1.9, 2.5, 4.2, 6.5, 9.0, 14.0],
    },
    tags: ["bold", "poster", "coral", "uppercase", "high-contrast", "energetic"],
    compositionRules: [
      "Three-surface system: coral fire / ink black / warm cream",
      "Bebas Neue uppercase tracked display + Inter body",
      "45° diagonal hatch on coral regions as signature texture",
      "Decorative wallpaper numerals in coral regions",
      "Hard color-region splits — zero radius except circles",
    ],
  },
  {
    id: "blockframe",
    name: "BlockFrame",
    palette: {
      ink: "#000000",
      canvas: "#FFFDF5",
      accents: ["#FE90E8", "#C0F7FE", "#99E885", "#F7CB46"],
      muted: "#666666",
    },
    typeRamp: {
      display: "Inter",
      heading: "Inter",
      body: "Inter",
      mono: "Space Grotesk",
      scale: [0.95, 1.15, 2.1, 3.3, 5.0],
    },
    tags: ["playful", "bold", "pastel", "retro", "neo-brutalist", "colorful", "fun"],
    compositionRules: [
      "4px black borders + 8px hard offset shadows",
      "Five-pastel candy palette (pink/blue/green/yellow/cream) plus black/white",
      "Inter 800–900 uppercase display + Space Grotesk label chrome",
      "Square corners, label-pills, tilted decorations, star bursts",
      "Stripe blocks and dot grids as poster decoration",
    ],
  },
  {
    id: "biennale-yellow",
    name: "Biennale Yellow",
    palette: {
      ink: "#1B2566",
      canvas: "#E9E5DB",
      accents: ["#F1EE2E", "#E26B4A"],
      muted: "#8A8575",
    },
    typeRamp: {
      display: "Instrument Serif",
      heading: "Instrument Serif",
      body: "Archivo",
      mono: "JetBrains Mono",
      scale: [0.85, 0.95, 1.55, 2.9, 4.6, 7.0, 14.6, 28.0],
    },
    tags: ["editorial", "warm", "serif", "solar", "art", "cultural", "light"],
    compositionRules: [
      "Warm parchment grounds with single deep indigo ink",
      "Solar yellow deployed as bloom / panel / tile underprint",
      "Instrument Serif display + Archivo sans + JetBrains Mono data",
      "1px hairline rules as the only border",
      "Atmospheric depth (no shadows) — sun bloom and ember bloom",
    ],
  },
  {
    id: "blue-professional",
    name: "Blue Professional",
    palette: {
      ink: "#111111",
      canvas: "#FDFBE7",
      accents: ["#1E2BFA"],
      muted: "#6B6B6B",
    },
    typeRamp: {
      display: "Space Grotesk",
      heading: "Space Grotesk",
      body: "Inter",
      mono: "JetBrains Mono",
      scale: [0.8, 0.85, 1.25, 2.6, 4.2, 8.0],
    },
    tags: ["professional", "clean", "data", "corporate", "tech", "minimal", "light"],
    compositionRules: [
      "Warm cream canvas with single saturated cobalt (#1e2bfa) as only accent",
      "Three-step gray text ladder",
      "Space Grotesk display/numerals/chrome + Inter body",
      "Soft cobalt-tinted cards (4% fill / 20% border / 10–14px radius) with NO shadows",
      "Cobalt progress bar as primary chrome",
    ],
  },
  {
    id: "bold-poster",
    name: "Bold Poster",
    palette: {
      ink: "#1C1410",
      canvas: "#FFFFFF",
      accents: ["#D8000F"],
      muted: "#8A7A70",
    },
    typeRamp: {
      display: "Shrikhand",
      heading: "Shrikhand",
      body: "Libre Baskerville",
      mono: "Space Grotesk",
      scale: [0.7, 0.85, 1.9, 3.3, 4.7, 10.4, 13.5, 22.0],
    },
    tags: ["bold", "poster", "retro", "typographic", "red", "dramatic", "high-contrast"],
    compositionRules: [
      "Four-color palette: white / brown-black ink / tomato red / off-white",
      "Three-face stack: Shrikhand display + Libre Baskerville serif + Space Grotesk mono",
      "Stacked text-shadow on red display (the ONLY shadow in the system)",
      "3px + 1.5px double-border grid as structural device",
      "Red leftbar cards, red em-dash bullets, red progress bar",
    ],
  },
  {
    id: "broadside",
    name: "Broadside",
    palette: {
      ink: "#111111",
      canvas: "#F0ECE5",
      accents: ["#E85D26"],
      muted: "#888880",
    },
    typeRamp: {
      display: "Barlow",
      heading: "Barlow",
      body: "Barlow",
      mono: "IBM Plex Mono",
      scale: [0.9, 1.2, 1.6, 2.8, 4.5, 7.5, 13.0],
    },
    tags: ["bold", "dark", "industrial", "manifesto", "high-impact", "editorial"],
    compositionRules: [
      "Two-register surface system: dark ink-black / fire-orange",
      "Massive Barlow in lowercase weight 900 treated as graphic primitive",
      "IBM Plex Mono chrome (uppercase, 0.14em)",
      "Single fire-orange accent on dark ground",
      "Flat plane with 1px hairline dividers",
    ],
  },
  {
    id: "code-editorial",
    name: "Code Editorial",
    palette: {
      ink: "#141413",
      canvas: "#FAF9F5",
      accents: ["#CC785C"],
      muted: "#7A7568",
    },
    typeRamp: {
      display: "EB Garamond",
      heading: "EB Garamond",
      body: "Inter",
      mono: "JetBrains Mono",
      scale: [1.35, 1.5, 2.08, 4.6, 6.7, 7.3, 9.9],
    },
    tags: ["editorial", "code", "warm", "serif", "technical", "refined", "light"],
    compositionRules: [
      "Warm cream paper (never pure white, never cool)",
      "Single terracotta coral as scarce voltage accent",
      "Hairline ink elevation (no heavy shadow)",
      "EB Garamond display + Inter body + JetBrains Mono code voice",
      "Coral spike mark (✱) as signature punctuation",
    ],
  },
  {
    id: "creative-mode",
    name: "Creative Mode",
    palette: {
      ink: "#0F0F0F",
      canvas: "#EFE9D9",
      accents: ["#1F8A4C", "#F06CA8", "#E85A1F", "#F5C518"],
      muted: "#6A6555",
    },
    typeRamp: {
      display: "Archivo Black",
      heading: "Archivo Black",
      body: "Space Grotesk",
      mono: "JetBrains Mono",
      scale: [1.25, 1.46, 1.77, 4.2, 6.4, 8.0, 11.0, 15.5],
    },
    tags: ["bold", "playful", "colorful", "brutalist", "creative", "high-energy", "uppercase"],
    compositionRules: [
      "Warm cream canvas with 4px ink borders",
      "Hard offset shadows (no blur) — the signature depth",
      "Archivo Black uppercase at 0.92 line-height for display",
      "JetBrains Mono taxonomy + Space Grotesk body",
      "Four-accent palette (green/pink/orange/yellow) on cream",
    ],
  },
  {
    id: "daisy-days",
    name: "Daisy Days",
    palette: {
      ink: "#2D2D2D",
      canvas: "#F5F0E6",
      accents: ["#7ECDC0", "#F7C8D4", "#FDE68A", "#F8635F"],
      muted: "#6B6B6B",
    },
    typeRamp: {
      display: "Fredoka One",
      heading: "Fredoka One",
      body: "Quicksand",
      mono: "JetBrains Mono",
      scale: [0.78, 0.95, 1.3, 1.8, 3.0, 4.5, 6.5],
    },
    tags: ["playful", "pastel", "sunny", "friendly", "soft", "cheerful", "light"],
    compositionRules: [
      "Sunny-garden pastel palette (cream + turquoise/pink/butter/mint/lavender/peach/sky)",
      "Charcoal 3px outlines with hard offset shadows (6/4px, no blur)",
      "Fredoka + Quicksand pairing — rounded, friendly",
      "Generous radii (20px/28px/50px pill)",
      "Headline text-shadow on color, dot bullets, hand-drawn SVG ornament layer",
    ],
  },
  {
    id: "editorial-forest",
    name: "Editorial Forest",
    palette: {
      ink: "#1A1A17",
      canvas: "#EFE7D4",
      accents: ["#2E4A2A", "#E89CB1"],
      muted: "#6A6A60",
    },
    typeRamp: {
      display: "Source Serif 4",
      heading: "Source Serif 4",
      body: "Source Serif 4",
      mono: "JetBrains Mono",
      scale: [1.25, 1.35, 1.56, 2.9, 4.4, 7.3, 11.5],
    },
    tags: ["editorial", "nature", "green", "serif", "calm", "refined", "warm"],
    compositionRules: [
      "Green/pink/cream editorial triad palette",
      "Source Serif 4 at weight 500 (optical-size axis) for all display",
      "JetBrains Mono 500 uppercase chrome",
      "Flat paper depth (no shadows), 2px hairline rules",
      "Monogram circle stamp as identity signature",
    ],
  },
]

/** Look up a preset by its id */
export function getPresetById(id: string): FramePreset | undefined {
  return FRAME_PRESETS.find((p) => p.id === id)
}
